import localFont from "next/font/local";
import "./globals.css";
import "./assets/scss/styles.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { Roboto } from 'next/font/google';
import HeaderHomeTemplate from "./templates/HeaderHomeTemplate";
import Footer from "./components/Footer/Footer";

const roboto = Roboto({ subsets: ['latin'], weight: ['300', '400', '700'] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
  alternates: {
    canonical: "https://shoesshopbc70.vercel.app",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <HeaderHomeTemplate />
        {children}
        <Footer />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" crossOrigin="anonymous"></script>
      </body>
    </html>
  );
}
